[build]
  command = "yarn build"
  publish = "dist"  # Ou o diretório de saída correto do seu projeto

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/old-path/*"
  to = "/new-path/:splat"
  status = 301