[build]
  command = "yarn install --frozen-lockfile && yarn add vite && yarn build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/old-path/*"
  to = "/new-path/:splat"
  status = 301