[build]
  command = "yarn install && yarn build"
  publish = "dist"
  
[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/old-path/*"
  to = "/new-path/:splat"
  status = 301